### ISSUE TITLE
Possible integer overflow

### ISSUE THREAD

**Issue by maxdeviant** [tuzz/game-loop#19]
The `number_of_updates` and `number_of_renders` counters have the potential to overflow.

I saw this while trying to use `game-loop` to run the game loop for a game server. Since the server is headless, I had an empty function for my `render`:

```rs
game_loop(
    game,
    60,
    0.1,
    |ctx| {
        ctx.game
            .update(Duration::from_secs_f64(ctx.fixed_time_step()))
    },
    |_| {},
);
```

After a brief period of time my server would panic due to an integer overflow when trying to increment `number_of_renders` once it reaches `u32::MAX`.

While this case is probably the most pathological one—as `render` isn't doing any work and can thus increment `number_of_renders` as quickly as possible—I suspect other users of this crate will run into the same issue eventually.

I'm not sure what the best way to go about fixing this would be, but it seems like having `number_of_updates` and `number_of_renders` being able to unboundedly increase is not desirable.

**Comment by tuzz** [comment]
Thanks for the issue report.

Would it be good enough to just make `number_of_updates` and `number_of_updates` a `u64` instead of `u32`? I can't see that these numbers would ever exceed 18446744073709551615 even in pathological cases - in which case there's probably a bug elsewhere in your program, anyway.

**Comment by parasyte** [comment]
`0_u64` can't overflow [in reasonable time](https://www.reddit.com/r/ProgrammerTIL/comments/4tspsn/c_it_will_take_approximately_97_years_to_overflow/) [^1] when incremented by 1. My vote is that this is the solution.

[^1]: I know that thread is kind of old and we have faster CPUs now. And I know it's talking about `i64` instead of `u64`. But The fact holds even at a ridiculous 8 GHz, incrementing a `u64` every clock cycle will take [73 years](https://www.wolframalpha.com/input?i=2%5E64+%2F+%288+*+1e9+*+86400+*+365%29) to overflow. Assuming you have actual work instead of dedicating a CPU core to incrementing a register, the length of time to overflow will increase dramatically.
